name: life_below_water_plus
description: Flutter demo with sqflite, StreamBuilder, shared_preferences, http+JSON + onboarding + auth + bottom navigation.
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  http: ^1.2.2
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4

  firebase_core: ^3.3.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.0.0
  firebase_messaging: ^15.2.10

  geolocator: ^10.1.0
  image_picker: ^1.0.7
  google_mobile_ads: ^5.0.0

  material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/species.json
    - assets/data/threats.json
    - assets/data/actions.json
